### ISSUE TITLE
Won't install on any PI or even a debian OS

### ISSUE THREAD

**Issue by sgrayban** [fabytm/Outage-Detector#2]
pip install Outage-Detector produces this error on all my Pi's I have which are 2/3/4

```
Collecting keyring==21.2.0 (from Outage-Detector)
  Could not find a version that satisfies the requirement keyring==21.2.0 (from Outage-Detector) (from versions: 0.0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.5.1, 0.6.2, 0.7, 0.7.1, 0.8, 0.8.1, 0.9, 0.9.1, 0.9.2, 0.9.3, 0.10, 0.10.1, 1.0, 1.1, 1.1.1, 1.1.2, 1.2.dev0, 1.2, 1.2.1, 1.2.2, 1.2.3, 1.3, 1.4, 1.5, 1.6, 1.6.1, 2.0, 2.0.1, 2.0.2, 2.0.3, 2.1, 2.1.1, 3.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.1, 3.2, 3.2.1, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 4.0, 4.1, 4.1.1, 5.0, 5.1, 5.2, 5.2.1, 5.3, 5.4, 5.5, 5.5.1, 5.6, 5.7, 5.7.1, 6.0, 6.1, 6.1.1, 7.0, 7.0.1, 7.0.2, 7.1, 7.1.1, 7.1.2, 7.2, 7.3, 7.3.1, 8.0, 8.0.1, 8.1, 8.1.1, 8.2, 8.3, 8.4, 8.4.1, 8.5, 8.5.1, 8.6, 8.6.1, 8.7, 9.0, 9.1, 9.2, 9.2.1, 9.3, 9.3.1, 10.0, 10.0.1, 10.0.2, 10.1, 10.2, 10.3, 10.3.1, 10.3.2, 10.3.3, 10.4.0, 10.5.0, 10.5.1, 10.6.0, 11.0.0, 11.1.0, 12.0.0, 12.0.1, 12.0.2, 12.1.0, 12.2.0, 12.2.1, 13.0.0, 13.1.0, 13.2.0, 13.2.1, 15.0.0, 15.1.0, 15.2.0, 16.0.0, 16.0.1, 16.0.2, 16.1.0, 16.1.1, 17.0.0, 17.1.0, 17.1.1, 18.0.0, 18.0.1, 19.0.0, 19.0.1, 19.0.2, 19.1.0, 19.2.0, 19.3.0, 20.0.0, 20.0.1, 21.0.0, 21.1.0)
No matching distribution found for keyring==21.2.0 (from Outage-Detector)
```

Building from the git sources I get the same error
`error: The 'keyrings.alt==3.4.0' distribution was not found and is required by Outage-Detector`

**Comment by fabytm** [comment]
I had someone report a very similar issue to me. Could you check which version of python you are using?

**Comment by sgrayban** [comment]
On most PI's you need to use the pip3 command instead of just pip. I got it installed when I looked at some of the code calling for python3.

So maybe telling users to try `pip3 install Outage-Detector` first if installing on a PI.

**Comment by fabytm** [comment]
You're right, I'll change that. I was curious which version of python3 specifically, the person who asked me about this has python3.5 installed, so maybe there's something up with keyring and older versions of python3. I tested this with python3.6(MacOS) and python3.7(Raspbian Buster).

**Comment by sgrayban** [comment]
You need python 3.6 or greater installed which means you need to have the raspbian buster installed to use this.

**Comment by sgrayban** [comment]
python 3.5 is debian stretch so PI's older then the 4 need to be upgraded to the newest Raspberry OS 
if that is even possible on those older PI's

**Comment by sgrayban** [comment]
Apparently keyring newest versions only work on python 3.6 or greater -- the last version that worked with 3.5 was 21.1.0 -- so older python3.5 wont work.

Sorry for the multi posts... its 2am here and im tired

**Comment by fabytm** [comment]
Yep, that's why I asked. It is possible to upgrade all models of Raspberry Pi to Buster, I actually did this on my 3B+ because I needed python 3.6 for something else before.

I will try testing my program with an older version of keyring this week and will come back with results (from your list, it seems to only look for versions up to 21.1.0). 

In the meantime, if you want to get this running, you could try just changing the requirement in `requirements.txt` file of the GitHub repo to look for version 21.1.0, it might work.

**Comment by sgrayban** [comment]
I could not get the app to work with python 3.5 at all. I worked on it for about 30 minutes using different package versions but the error always landed with a error not finding `keyrings.alt.kwallet` which apparently is only in the newest version of `keyrings.alt`

So it will not work on stretch -- also the crontab is being created wrong.
outage_detector is actually being created in `/usr/local/bin/` and not `/usr/bin/` so I had to change my cron for that.

**Comment by p1r473** [comment]
I am having a similar issue
I am on a TinkerBoard S
Apparently, keyrings.alt 3.4.0 is not available. But, I can select 3.2.0.

I did try pip3 instead of pip.

@fabytm can you check if you can get the tool to work with 3.2.0?

```
root@Harbormaster:/home/linaro/Outage-Detector # pip3 install keyrings.alt==3.4.0
Collecting keyrings.alt==3.4.0
  Could not find a version that satisfies the requirement keyrings.alt==3.4.0 (from versions: 1.0, 1.0.1, 1.1, 1.1.1, 1.2, 1.3, 2.0, 2.1, 2.2, 2.3, 2.4, 3.0, 3.1, 3.1.1, 3.2.0)
No matching distribution found for keyrings.alt==3.4.0
```

**Comment by sgrayban** [comment]
Edit the requirements.txt and edit the versions and see if you can get it to work... in all my tries it simply will not work with python 3.5 at all.

**Comment by p1r473** [comment]
Currently trying to upgrade my Python
```
sudo apt-get install python3-dev libffi-dev libssl-dev -y
wget https://www.python.org/ftp/python/3.8.3/Python-3.8.3.tar.xz
cd /home/linaro/Python3.8.3/
tar xJf Python3.8.3.tar.xz
cd Python-3.8.3
./configure
make
sudo make install
sudo pip3 install --upgrade pip
```
Will let you know if it works...

**Comment by p1r473** [comment]
> I could not get the app to work with python 3.5 at all. I worked on it for about 30 minutes using different package versions but the error always landed with a error not finding `keyrings.alt.kwallet` which apparently is only in the newest version of `keyrings.alt`
> 
> So it will not work on stretch -- also the crontab is being created wrong.
> outage_detector is actually being created in `/usr/local/bin/` and not `/usr/bin/` so I had to change my cron for that.

Outage detector looks like it made the crons okay for me
```
*/5 * * * * /usr/local/bin/python3.8 /usr/local/bin/outage_detector --run scheduled --notify notification >> /root/.config/outagedetector/log.txt 2>/root/.config/outagedetector/errors.txt
@reboot sleep 60 && /usr/local/bin/python3.8 /usr/local/bin/outage_detector --run boot --notify notification >> /root/.config/outagedetector/log.txt 2>/root/.config/outagedetector/errors.txt

```

**Comment by sgrayban** [comment]
Odd it didnt work for me -- I wonder if there is a difference between the git clone source and the pip3 install

**Comment by p1r473** [comment]
Try ```python3.8``` instead of ```python3``` when you call the installer.

**Comment by nevillator-999** [comment]
I found it worked if you install via the virtual environment _only_. I was having similar issues trying to install the first (few) times and upgrading Python, using pip3, etc.

> sudo apt-get install python3-venv  ##makes sure you have the right version of Python
> mkdir python ##make a directory to hold your virtual environments
> cd python/ 
> python3 -m venv ven ##makes a Python virtual environment call "ven"
> . ven/bin/activate  ##starts the virtual environment
> pip install Outage-Detector. ##installs the Outage-Detector files
> outage_detector --init. ##to setup and activate

After setting up using the Pushbullets API key I did not get the option to setup crons or scheduling, so still working on that.

**Comment by p1r473** [comment]
> I found it worked if you install via the virtual environment _only_. I was having similar issues trying to install the first (few) times and upgrading Python, using pip3, etc.
> 
> > sudo apt-get install python3-venv  ##makes sure you have the right version of Python
> > mkdir python ##make a directory to hold your virtual environments
> > cd python/
> > python3 -m venv ven ##makes a Python virtual environment call "ven"
> > . ven/bin/activate  ##starts the virtual environment
> > pip install Outage-Detector. ##installs the Outage-Detector files
> > outage_detector --init. ##to setup and activate
> 
> After setting up using the Pushbullets API key, I setup the crons and seems to be working so far.

Python 3.8.3 steps didn't work for you?
Why do you need a virtual environment for this?

**Comment by fabytm** [comment]
@p1r473 I will test it outside a virtual environment and update it so that it'll work outside a venv. It will take some time as I got a lot of feature requests and a few bugs pointed out to me after my project has been featured on Tom's Hardware.

**Comment by p1r473** [comment]
@fabytm I was able to get it working by installing Python 3.6+ (I installed 3.8.3 but I saw a 3.9 was up, not sure if its beta though)
If you can get it to work with 3.5, that would be better for compatability.

**Comment by fabytm** [comment]
@p1r473 I will see what I can do about keyring and Python 3.5. There's always the option of dropping keydrop's secure password storage for Python3.5 and lower but I'm not sure if the tradeoff is worth it.

Thank you!

**Comment by p1r473** [comment]
@fabytm There are other ways to encrypt the files without using keydrop!

**Comment by p1r473** [comment]
@fabytm is Python 3.5 support fixed?
Can you re-open this issue until it is fixed?
Thanks!

**Comment by sgrayban** [comment]
I closed it... I don't think an official fix for python 3.5 is going to happen.

**Comment by fabytm** [comment]
@p1r473 I reopened it. The issue isn't fixed as I haven't had time to install python3.5 in a Linux VM yet (pretty busy with finals, what I pushed today was a quick change to the way I'm saving the PushBullet keys).

**Comment by p1r473** [comment]
@fabytm any luck with Python 3.5?

**Comment by fabytm** [comment]
@p1r473 I haven't had a change to look at it, but just today I received a PM from someone facing the same issue on Python 3.5 and they seem to have fixed it by running:

`
sudo apt-get install python-pip (after already having pip3 python3 installed) 
pip install pybin 
pybin put -h 
sudo reboot
`

**Comment by p1r473** [comment]
> @p1r473 I haven't had a change to look at it, but just today I received a PM from someone facing the same issue on Python 3.5 and they seem to have fixed it by running:
> 
> `sudo apt-get install python-pip (after already having pip3 python3 installed)`
> `pip install pybin`
> `pybin put -h`
> `sudo reboot`

Last command doesn't seem to work
# pybin put -h
```
Usage: pybin put [OPTIONS]

  Updates the user PATH. The shell must be restarted for the update to take
  effect.

Options:
  -p, --pypath TEXT  An absolute path to a Python executable.
  -f, --force        Update PATH even if it appears to be correct.
  -h, --help         Show this message and exit.
```

**Comment by p1r473** [comment]
Can you get rid of Keyring and use something else to encrypt the API keys and passwords?

**Comment by fabytm** [comment]
I don’t know of a good alternative to keyring unfortunately.

I’ll try contacting the guy who said he managed to fix this issue by running those commands to see if he didn’t do anything besides running those commands.

**Comment by p1r473** [comment]
> I don’t know of a good alternative to keyring unfortunately.
> 
> I’ll try contacting the guy who said he managed to fix this issue by running those commands to see if he didn’t do anything besides running those commands.

What about previous versions of Keyring?
Why do I need the latest version of Keyring? Can you not make it work with older Keyrings?

The easiest way is probably to accept the password, then encrypt it with YOUR private key that only you know. Then, all that is saved is the encrypted password.

Other options:
https://www.vidarholen.net/contents/blog/?p=32 Using md5sum to store the hash of the password
https://www.raspberrypi.org/forums/viewtopic.php?t=123228 Storing it in a password protected sqlite3 database

**Comment by p1r473** [comment]
@fabytm would really love this to work on Python 3.5 please :)

**Comment by p1r473** [comment]
> I found it worked if you install via the virtual environment _only_. I was having similar issues trying to install the first (few) times and upgrading Python, using pip3, etc.
> 
> > sudo apt-get install python3-venv  ##makes sure you have the right version of Python
> > mkdir python ##make a directory to hold your virtual environments
> > cd python/
> > python3 -m venv ven ##makes a Python virtual environment call "ven"
> > . ven/bin/activate  ##starts the virtual environment
> > pip install Outage-Detector. ##installs the Outage-Detector files
> > outage_detector --init. ##to setup and activate
> 
> After setting up using the Pushbullets API key, I setup the crons and seems to be working so far.

But the Virtual Environment is still 3.5 so still same issue
```
root@Harbormaster:/home/linaro# mkdir PythonVirtualEnvironment
root@Harbormaster:/home/linaro# cd Python
-bash: cd: Python: No such file or directory
root@Harbormaster:/home/linaro# cd P
Pictures/                 Public/                   Python3.8.3.tar.xz        PythonVirtualEnvironment/
root@Harbormaster:/home/linaro# cd P
Pictures/                 Public/                   Python3.8.3.tar.xz        PythonVirtualEnvironment/
root@Harbormaster:/home/linaro# cd PythonVirtualEnvironment/
root@Harbormaster:/home/linaro/PythonVirtualEnvironment# python3 -m venv ven
root@Harbormaster:/home/linaro/PythonVirtualEnvironment# . ven/bin/activate
(ven) root@Harbormaster:/home/linaro/PythonVirtualEnvironment# pip install Outage-Detector
Collecting Outage-Detector
  Using cached https://files.pythonhosted.org/packages/03/01/7f16fb6ff42010cd57bc4bf94aaa11525e7b847fcedfa00b9b3d5e6a7c77/Outage_Detector-1.1.1-py3-none-any.whl
Collecting six==1.13.0 (from Outage-Detector)
  Downloading https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl
Collecting chardet==3.0.4 (from Outage-Detector)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 1.4MB/s
Collecting websocket-client==0.56.0 (from Outage-Detector)
  Using cached https://files.pythonhosted.org/packages/29/19/44753eab1fdb50770ac69605527e8859468f3c0fd7dc5a76dd9c4dbd7906/websocket_client-0.56.0-py2.py3-none-any.whl
Collecting python-magic==0.4.15 (from Outage-Detector)
  Using cached https://files.pythonhosted.org/packages/42/a1/76d30c79992e3750dac6790ce16f056f870d368ba142f83f75f694d93001/python_magic-0.4.15-py2.py3-none-any.whl
Collecting requests==2.22.0 (from Outage-Detector)
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Collecting keyrings.alt==3.4.0 (from Outage-Detector)
  Could not find a version that satisfies the requirement keyrings.alt==3.4.0 (from Outage-Detector) (from versions: 1.0, 1.0.1, 1.1, 1.1.1, 1.2, 1.3, 2.0, 2.1, 2.2, 2.3, 2.4, 3.0, 3.1, 3.1.1, 3.2.0)
No matching distribution found for keyrings.alt==3.4.0 (from Outage-Detector)
(ven) root@Harbormaster:/home/linaro/PythonVirtualEnvironment#
```

**Comment by p1r473** [comment]
Got it working.... just had to change requirements.txt
```
keyring==21.2.0
keyrings.alt==3.4.0
keyring
keyrings.alt
```

**Comment by fabytm** [comment]
Great, I'm glad it works! Would you be so kind as to tell me what version of keyring and keyrings.alt it installs under Python 3.5?

**Comment by p1r473** [comment]
How can I tell? Looks like the above command installed 0.0.0
```pip3 freeze | grep keyring
keyring==0.0.0
keyrings.alt==0.0.0
```
