### ISSUE TITLE
Encrypt Pushbullet Key

### ISSUE THREAD

**Issue by p1r473** [fabytm/Outage-Detector#4]
Hello,
Please consider encrypting the Pushbullet key so it is not sitting in plaintext on the drive.
Thanks.

**Comment by fabytm** [comment]
Hello, the mail password is stored using keyring, so it should be more secure than plaintext. I considered doing this for Pushbullet too but I figured it wasn't as sensitive. 

Although, now that I think of it, if someone gets the key, they could spam you which is not ok, so I will treat the PushBullet key the same way I do mail passwords.

I hope this answers your question.

**Comment by p1r473** [comment]
Yes, please do for Pushbullet API too. This is the one I am using (not using mail so didn't check if it was encrypted)

**Comment by fabytm** [comment]
Fixed in v1.1
