### ISSUE TITLE
IFTTT Support

### ISSUE THREAD

**Issue by ThatWeirdAndrew** [fabytm/Outage-Detector#5]
I've been working on adding IFTTT support to outage detector but I would like your opinion on it before I continue more. I already use IFTTT for many things and it would be more convenient to receive outage notifications through it.

I wasn't sure if you would be fine with it or would rather keep it to one push notification service.

**Comment by fabytm** [comment]
Sounds great, I don't want to limit it to Pushbullet only. I haven't used IFTTT that much, how would it integrate with Outage-Detector functionality wise?

**Comment by ThatWeirdAndrew** [comment]
In IFTTT you would create a webhook event and choose an action. This could be many things like send a notification, send an email, or add the outage to a spreadsheet. Outage-Detector would send a post request to a url based on the event name and the api key and the action you chose would run.

**Comment by fabytm** [comment]
That would be really useful, as it would allow people to extend the functionality with IFTTT.
