### ISSUE TITLE
pip3 install Outage-Detector doesn't update prior version

### ISSUE THREAD

**Issue by jaaabeee** [fabytm/Outage-Detector#7]
Had previously installed older version. Trying to install v1.1. Running pip3 install Outage-Detector results in "Requirement already satisfied" for each requirement. Running outage-detector --init doesn't give option for IFTTT.

Can remove old installation manually, but believe installer should detect previous installs and handle gracefully. :-)

**Comment by jaaabeee** [comment]
Did a pip3 uninstall of the old version and new version installed successfully. Love the IFTTT integration!

**Comment by fabytm** [comment]
Did you try updating using the following syntax:

`pip3 install Outage-Detector --upgrade`

I updated my Raspberry Pis this way and I had no issues.

**Comment by jaaabeee** [comment]
Yep, that works. Worth updating the ReadMe with this.
Another note: the setup should be consistent about required y/n responses. Some questions require "yes" and some require "y". Most at least give the valid choices, but the final question for IFTTT configuration (setting up the crontab) doesn't give them, and typing "y" exits without doing anything. Looking at the source, I see the required answer is "yes"

**Comment by fabytm** [comment]
You're right, I'll update both! Thanks!

**Comment by fabytm** [comment]
@jaaabeee Both suggestions have been coded into v1.1.1 

[https://github.com/fabytm/Outage-Detector/releases/tag/v1.1.1](url)
